# name: "user-web"
# version: "1.0.0"
# ip: "127.0.0.1"
# port: 8081

# user_srv:
#   name: "user-srv"
#   host: "127.0.0.1"
#   port: 8080

# jwt:
#   key: "verysecret"
#   exp: 86400
#   issuer: "user-web"

# redis:
#   host: "127.0.0.1"
#   port: 6379

# consul:
#   host: "127.0.0.1"
#   port: 8500


# nacos:
host: "127.0.0.1"
port: 8848
namespace: "feb9807c-cdbf-41d0-bdda-4dc4a2f39c5d"
data_id: "user-web"
group: "dev"