# name: "good-srv"
# host: "127.0.0.1"
# port: 8080

# mysql:
#   host: "127.0.0.1"
#   port: 3306
#   user: "root"
#   password: "root123456"
#   db_name: "shop_good_srv"

# consul:
#   host: "127.0.0.1"
#   port: 8500

# nacos:
host: "127.0.0.1"
port: 8848
namespace: "841b0151-0e97-4771-a897-0f33aa5e5f9d"
data_id: "good-srv"
group: "dev"