name: "user-web"
version: "1.0.0"
ip: "127.0.0.1"
port: 8081

user_srv:
  name: "user-srv"
  host: "127.0.0.1"
  port: 8080

jwt:
  key: "verysecret"
  exp: 86400
  issuer: "user-web"

redis:
  host: "127.0.0.1"
  port: 6379

consul:
  host: "127.0.0.1"
  port: 8500